name: GoodSociety
favicon: null
layout_spectrum: 0.4649498511571437
typography_spectrum: 0.4351115976460278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5659235448110849
  lightness: 0.29184861993417144
  saturation: 0.13517612498253584
  rhythmicContrast: 0.4848566702567041
purpose: []
