name: GoodSociety
favicon: null
layout_spectrum: 0.4649498511571437
typography_spectrum: 0.4351115976460278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0801'
    - '#2a2522'
    - '#aeab9d'
    - '#484244'
    - '#7f7c75'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
